[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
# ===== Tauri core =====
tauri = { version = "2.11.3", features = [] }
tauri-plugin-log = "2"
tauri-plugin-process = "2.3.1"

# ===== Sérialisation =====
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# ===== Logging =====
log = "0.4"

# ===== Infos système =====
sysinfo = "0.38"

# ===== Réseau =====
reqwest = { version = "0.13", features = ["blocking"] }
local-ip-address = "0.6"

# ===== Ping natif (sans CMD/PowerShell) =====
surge-ping = "0.9"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "net", "time", "macros"] }

# ===== Notifications (natif) =====
tauri-plugin-notification = "2.4.0"

# ===== Impression thermique =====
tauri-plugin-thermal-printer = "2.1.4"
thermoprint = "0.3.0"
serialport = "4.10.1"

# ===== Calculs monétaires =====
rust_decimal = { version = "1.43.0", features = ["macros"] }
tauri-plugin-deep-link = "2.4.10"
tauri-plugin-single-instance = { version = "2.4.4", features = ["deep-link"] }
autostart = "0.1.0"
dialog = "0.3.0"
tauri-plugin-dialog = "2"

# ===== Plugins conditionnels (desktop uniquement) =====
[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-autostart = "2"
tauri-plugin-updater = "2"


# ===== API Windows native pour l'impression =====
[target.'cfg(windows)'.dependencies]
tauri-winrt-notification = "0.8"
rodio = "0.21.1"
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_Graphics_Printing",
    "Win32_Graphics_Gdi",
    "Win32_Storage_Xps",
    "Win32_UI",
    "Win32_UI_WindowsAndMessaging",
] }
